name: appwrite_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  appwrite: ^4.0.1
  google_fonts: 2.3.1
  connectivity_plus: 2.2.1
  intl: 0.17.0
  responsive_framework: 0.1.7
  get_storage: 2.0.3
  flutter_form_builder: 7.1.1
  form_builder_validators: 7.6.1
  fluttertoast: 8.0.9
  convex_bottom_bar: 3.0.0
  geolocator: 8.2.0
  geocoding: 2.0.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

